// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Order struct {
	OrderID         int32          `json:"order_id"`
	OrderNumber     string         `json:"order_number"`
	ProductName     string         `json:"product_name"`
	Quantity        int32          `json:"quantity"`
	ProductID       sql.NullInt32  `json:"product_id"`
	AdditionalShelf sql.NullString `json:"additional_shelf"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Product struct {
	ID          int64           `json:"id"`
	Title       string          `json:"title"`
	Active      sql.NullBool    `json:"active"`
	Price       sql.NullFloat64 `json:"price"`
	Description sql.NullString  `json:"description"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type ProductShelf struct {
	ID        sql.NullInt32 `json:"id"`
	ShelfID   sql.NullInt32 `json:"shelf_id"`
	IsPrimary sql.NullBool  `json:"is_primary"`
}

type Shelf struct {
	ShelfID   int32  `json:"shelf_id"`
	ShelfName string `json:"shelf_name"`
}

type User struct {
	ID        int64     `json:"id"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
